import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const product = await prisma.product.findMany();
  if (product.length === 0) {
    await prisma.product.createMany({
      data: [
        {
          name: "Aquele c/presunto 1° Temporada",
          price: 11,
          photoUrl: "https://i.im.ge/2023/04/17/LLETd1.AQUELE-C-PRESUNTO-2T-IFOOD.png",
          description: "Pão, bife de 56gr, presunto, alface, tomate, milho verde, batata palha, e Maionese Friends. ",
          category: "T1",
        },
        {
          name: "Aquele Duplo Picanha 1° Temporada",
          price: 25,
          photoUrl: "https://i.im.ge/2023/04/17/LLEbqP.PICANHA2.jpg",
          description: "Pão Brioche, 2 bife de Picanha 90gr, bacon, cebola, Catupiry ou Chedder e Maionese Friends. ",
          category: "T1",
        },
        {
          name: "Aquele c/ Calabresa 1° Temporada",
          price: 17.50,
          photoUrl: "https://i.im.ge/2023/04/17/LLCVJX.AQUELE-C-CALABRESA-IFOOD.png",
          description: "Pão, bife de 56 gr, linguiça calabresa, queijo, presunto, ovo, alface, tomate, milho verde, batata palha e Maionese Friends. ",
          category: "T1",
        },
        {
          name: "Aquele Hambúrguer 1° Temporada",
          price: 8,
          photoUrl: "https://i.im.ge/2023/04/17/LLCHfM.AQUELE-HAMBURGUER-IFOOD.png",
          description: "Pão, bife de 56g, alface, tomate, milho verde, batata palha, e Maionese Friends.",
          category: "T1",
        },
        {
          name: "Aquele Burg 1° Temporada",
          price: 12,
          photoUrl: "https://i.im.ge/2023/04/17/LLCWMF.AQUELE-BURG-IFOOD.png",
          description: "Pão, bife de 56gr, queijo, presunto, alface, tomate, milho verde, batata palha, e Maionese Friends",
          category: "T1",
        },
        {
          name: "Aquele c/ Egg 1° Temporada",
          price: 13,
          photoUrl: "https://i.im.ge/2023/04/17/LLCKE9.AQUELE-C-EGG-IFOOD.png",
          description: "Pão, bife de 56g, ovo, queijo, presunto, alface, tomate, milho verde, batata palha, e Maionese Friends",
          category: "T1",
        },
        {
          name: "Aquele Tudo 1° Temporada",
          price: 16.50,
          photoUrl: "https://i.im.ge/2023/04/17/LLCZDK.AQUELE-TUDO-IFOOD.png",
          description: "Pão, bife de 56gr, queijo, bacon, presunto, ovo, alface, tomate, milho verde, batata palha, e Maionese Friends.",
          category: "T1",
        },
        {
          name: "Aquele c/Bacon R$ 14,50 1° Temporada",
          price: 14.50,
          photoUrl: "https://i.im.ge/2023/04/17/LLCkS8.AQUELE-C-BACON-IFOOD.png",
          description: "Pão, 1 bife de 56gr, bacon, queijo, presunto, alface, tomate, milho verde, batata palha, e Maionese Friends.",
          category: "T1",
        },
        {
          name: "Aquele TRIPLO BIG 1° Temporada",
          price: 24.50,
          photoUrl: "https://i.im.ge/2023/04/17/LLEaPa.AQUELE-TRIPLO-BIG-IFOOD.png",
          description: "Pão, 2 bifes de 56gr, 2 queijos, 2 presuntos, bacon, 2 ovos ,alface, tomate, milho verde, batata palha e Maionese Friends.",
          category: "T2",
        },
        {
          name: "Aquele Hambúrguer 2° Temporada",
          price: 10,
          photoUrl: "https://i.im.ge/2023/04/17/LLCvrY.AQUELE-HAMBURGUER-2T.png",
          description: "Pão, 2 bifes de bife de 56g, alface, tomate, milho verde, batata palha, e Maionese Friends.",
          category: "T2",
        },
        {
          name: "Aquele c/ calabresa  2° Temporada",
          price: 20,
          photoUrl: "https://i.im.ge/2023/04/17/LLCGIq.AQUELE-C-CALABRESA-2T-IFOOD.png",
          description: "Pão, 2 bifes de 56 gr, linguiça calabresa, queijo, presunto, ovo, alface, tomate, milho verde, batata palha e Maionese Friends.",
          category: "T2",
        },
        {
          name: "Aquele Burg 2° Temporada",
          price: 14,
          photoUrl: "https://i.im.ge/2023/04/17/LLCng4.AQUELE-BURG-2T-IFOOD.png",
          description: "Pão, 2bifes de de 56gr, queijo,presunto  alface, tomate, milho verde, batata palha e Maionese Friends.",
          category: "T2",
        },
        {
          name: "Aquele Tudo  2° Temporada",
          price: 19.50,
          photoUrl: "https://i.im.ge/2023/04/17/LLCJ5D.AQUELE-TUDO-2T-IFOOD.png",
          description: "Pão, 2 bifes de 56g, queijo, bacon, presunto, ovo, alface, tomate, milho verde, batata palha e Maionese Friends",
          category: "T2",
        },
        {
          name: "Aquele com chicken 2° Temporada",
          price: 19,
          photoUrl: "https://i.im.ge/2023/04/17/LLCeEp.AQUELE-C-CHICKEN-2T-IFOOD.png",
          description: "Pão, frango desfiado com ovo, queijo, bacon, presunto, milho, batata palha e Maionese Friends.",
          category: "T2",
        },
        {
          name: "Aquele Double BIG 2° Temporada",
          price: 22.50,
          photoUrl: "https://i.im.ge/2023/04/17/LLE7fJ.AQUELE-DOUBLE-BIG-IFOOD.png",
          description: "Pão, 2 bifes de 56gr, 2 queijos, 2 presuntos bacon, 2 ovos ,alface, tomate, milho verde, batata palha e Maionese Friends.",
          category: "T2",
        },
        {
          name: "Aquele c/ bacon 2 ° Temporada",
          price: 17.50,
          photoUrl: "https://i.im.ge/2023/04/17/LLCBMC.AQUELE-C-BACON-2T-IFOOD.png",
          description: "Pão, 2 bifes de 56gr, bacon, queijo, presunto, alface, tomate, milho verde, batata palha, e Maionese Friends.",
          category: "T2",
        },
        {
          name: "X-Mike Artesanal",
          price: 22.50,
          photoUrl: "https://i.im.ge/2023/04/17/LLEwP8.X-MIKE-IFOOD.png",
          description: "Pão, carne de 120g, linguiça calabresa, cebola,queijo e Maionese Friends.",
          category: "Artesanais",
        },
        {
          name: "X-Onion Rings Artesanal",
          price: 19,
          photoUrl: "https://i.im.ge/2023/04/17/LLEL9S.X-ONION-IFOOD.png",
          description: "Pão, carne de 120g, queijo, maionese caseira, Onion (anel de cebola) e Maionese Friends",
          category: "Artesanais",
        },
        {
          name: "X-Chandler Artesanal",
          price: 19,
          photoUrl: "https://i.im.ge/2023/04/17/LLEiQ6.X-CHANDLER-IFOOD.png",
          description: "Pão, carne de 120g, queijo, cheddar cremoso e Maionese Friends",
          category: "Artesanais",
        },
        {
          name: "X-Mônica Artesanal",
          price: 15,
          photoUrl: "https://i.im.ge/2023/04/17/LLEIuy.X-MONICA-IFOOD.png",
          description: "Pão, carne de 120g , queijo e Maionese Friends",
          category: "Artesanais",
        },
        {
          name: "X-Ross Artesanal",
          price: 20.50,
          photoUrl: "https://i.im.ge/2023/04/17/LLEU8z.X-ROSS-IFOOD.png",
          description: "Pão, carne de 120g, bacon picado, ovo, queijo e Maionese Friends.",
          category: "Artesanais",
        },
        {
          name: "X-Joey Artesanal",
          price: 19.50,
          photoUrl: "https://i.im.ge/2023/04/17/LLEmqX.X-JOEY-IFOOD.png",
          description: "Pão, carne de 120g, bacon, queijo e Maionese Friends",
          category: "Artesanais",
        },
        {
          name: "X-Gunter Artesanal",
          price: 21.50,
          photoUrl: "https://i.im.ge/2023/04/17/LLE5xK.X-GUNTER-IFOOD.png",
          description: "Pão, carne 120g, queijo, bacon, cheddar e Maionese Friends",
          category: "Artesanais",
        },
        {
          name: "X-Emily Artesanal",
          price: 17,
          photoUrl: "https://i.im.ge/2023/04/17/LLE0LF.X-EMILY-IFOOD.png",
          description: "Pão, carne de 120g, queijo, ovo e Maionese Friends",
          category: "Artesanais",
        },
        {
          name: "X-Janice Artesanal",
          price: 26,
          photoUrl: "https://i.im.ge/2023/04/17/LLE9n9.X-JANICE-IFOOD.png",
          description: "Pão, duas carne de 120g, queijo, cheddar e Maionese Friends",
          category: "Artesanais",
        },
        {
          name: "Combo Kids",
          price: 13,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202107091417_T56U_i.jpg",
          description: "Aquele burger, Fritas 150gr, suco tial e bala fine",
          category: "Combos",
        },
        {
          name: "Combo Aquele burger",
          price: 60,
          photoUrl: "https://i.im.ge/2023/04/17/LLE1QT.COMBO-AQUELE-BURG-IFOOD.png",
          description: "3 Aquele burger,Fritas 350gr com chedder, calabresa  e Maionese Friends",
          category: "Combos",
        },
        {
          name: "Combo Aquele Tudo",
          price: 74,
          photoUrl: "https://i.im.ge/2023/04/17/LLEu5W.COMBO-AQUELE-BUEGUER-IFOOD.png",
          description: "3 Aquele Tudo, Fritas 350gr com chedder, calabresa , Refri 2 litros e Maionese Friends",
          category: "Combos",
        },
        {
          name: "Combo Casal Aquele Tudo",
          price: 58,
          photoUrl: "https://i.im.ge/2023/04/17/LLEu5W.COMBO-AQUELE-BUEGUER-IFOOD.png",
          description: "2 Aquele Tudo, Fritas 350gr, calabresa, Refri 2 litros e Maionese Friends",
          category: "Combos",
        },
        {
          name: "Combo Ross Geller",
          price: 27,
          photoUrl: "https://i.im.ge/2023/04/17/LLErur.COMBO-ROSS-IFOOD.png",
          description: "Aquele Burg, Fritas 200 gramas, Coca Cola Lata 350ml e Maionese Friends.",
          category: "Combos",
        },
        {
          name: "Combo Chandler Bing",
          price: 51,
          photoUrl: "https://i.im.ge/2023/04/17/LLEF80.COMBO-CHANDLER-IFOOD.png",
          description: "2 Aquele c/Bacon, Fritas 350gr, Kuat 2l e Maionese Friends",
          category: "Combos",
        },
        {
          name: "Combo Monica Geller",
          price: 62,
          photoUrl: "https://i.im.ge/2023/04/17/LLESxL.COMBO-MONICA-IFOOD.png",
          description: " 3 Aquele Burg, Fritas 350gr, Coca-Cola 1,5l e Maionese Friends",
          category: "Combos",
        },
        {
          name: "Combo Drake Ramoray",
          price: 61,
          photoUrl: "https://i.im.ge/2023/04/17/LLE2Ic.COMBO-DRAKE-IFOOD.png",
          description: " 2 Aquele Burg, Fritas 350gr, Coca-Cola 1,5l e Maionese Friends",
          category: "Combos",
        },
        {
          name: "Combo Rachel Green",
          price: 46,
          photoUrl: "https://i.im.ge/2023/04/17/LLEdJG.COMBO-RACHEL-IFOOD.png",
          description: "2 Aquele Egg, Fritas 350gr, Kuat 2l e Maionese Friends",
          category: "Combos",
        },
        {
          name: "Batata Friends Pequena",
          price: 8,
          photoUrl: "https://i.im.ge/2023/04/17/LLEXfm.BATATA-FRITA-IFOOD.png",
          description: "Batata Frita 200gr",
          category: "Porções",
        },
        {
          name: "Batata Friends Grande",
          price: 20,
          photoUrl: "https://i.im.ge/2023/04/17/LLEXfm.BATATA-FRITA-IFOOD.png",
          description: "Batata Frita 350gr, Cheddar ou Catupiry e Bacon ou Calabresa",
          category: "Porções",
        },
        {
          name: "Nuggets Friends",
          price: 12,
          photoUrl: "https://www.designi.com.br/images/preview/10618483-m.jpg",
          description: "8 Unidades e Maionese Friends",
          category: "Porções",
        },
        {
          name: "Chokito",
          price: 4.25,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202107091329_U05M_i.jpg",
          description: "",
          category: "Bombonière",
        },
        {
          name: "Prestígio",
          price: 4.25,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202107091329_0L7U_i.jpg",
          description: "",
          category: "Bombonière",
        },
        {
          name: "Halls",
          price: 4,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202107091058_3o83_p.png",
          description: "",
          category: "Bombonière",
        },
        {
          name: "Trento",
          price: 4,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202107091331_K6L2_i.jpg",
          description: "",
          category: "Bombonière",
        },
        {
          name: "Trident",
          price: 4,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202107091058_7cV8_p.jpg",
          description: "",
          category: "Bombonière",
        },
        {
          name: "Fini",
          price: 3,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202107091335_IYPI_i.jpg",
          description: "",
          category: "Bombonière",
        },
        {
          name: "Brahma Latão",
          price: 9,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/820af392-002c-47b1-bfae-d7ef31743c7f/202210192154_5zll406nhvw.jpg",
          description: "473ml",
          category: "Cervejas",
        },
        {
          name: "Heineken Garrafa",
          price: 18,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/820af392-002c-47b1-bfae-d7ef31743c7f/202210190040_6g7rha4jac8.jpg",
          description: "600ml",
          category: "Cervejas",
        },
        {
          name: "Heineken Lata",
          price: 8,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/820af392-002c-47b1-bfae-d7ef31743c7f/202302102112_flu23ungl2w.jpg",
          description: "350ml",
          category: "Cervejas",
        },
        {
          name: "Stella Garrafa",
          price: 15,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202209301939_QW25_i.jpg",
          description: "600ml",
          category: "Cervejas",
        },
        {
          name: "AÇAÍ C/ MORANGO 300ML",
          price: 15,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202207181917_EGx4_p.jpg",
          description: "+ 3 Complementos",
          category: "Açai",
        },
        {
          name: "AÇAÍ C/ MORANGO 500ML",
          price: 18,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202207181917_EGx4_p.jpg",
          description: "+ 3 Complementos",
          category: "Açai",
        },
        {
          name: "AÇAÍ C/ BANANA 300ML",
          price: 13,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202207181949_ysAZ_p.jpg",
          description: "+ 3 Complementos",
          category: "Açai",
        },
        {
          name: "AÇAÍ C/ BANANA 500ML",
          price: 16,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202207181949_ysAZ_p.jpg",
          description: "+ 3 Complementos",
          category: "Açai",
        },
        {
          name: "Coca Cola Lata",
          price: 6,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202107091252_A8JR_i.jpg",
          description: "350ml",
          category: "Bebidas",
        },
        {
          name: "Fanta Laranja Lata",
          price: 5.50,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/820af392-002c-47b1-bfae-d7ef31743c7f/202210192348_isn9iesta4.jpg",
          description: "350ml",
          category: "Bebidas",
        },
        {
          name: "Kuat Lata",
          price: 4.50,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202107091408_754I_i.jpg",
          description: "350ml",
          category: "Bebidas",
        },        {
          name: "Sprite Lata",
          price: 6,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/820af392-002c-47b1-bfae-d7ef31743c7f/202210192208_8uoawvxjosp.jpg",
          description: "Sprite Original 350ml",
          category: "Bebidas",
        },
        {
          name: "H2OH Limoneto",
          price: 10.50,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/820af392-002c-47b1-bfae-d7ef31743c7f/202210192139_mtimlpz852.jpg",
          description: "1,5L",
          category: "Bebidas",
        },
        {
          name: "H20H Limão",
          price: 8.50,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/820af392-002c-47b1-bfae-d7ef31743c7f/202210192139_mtimlpz852.jpg",
          description: "1,5L",
          category: "Bebidas",
        },
        {
          name: "Kapo",
          price: 3.50,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202107091255_00T2_i.jpg",
          description: "350ml",
          category: "Bebidas",
        },
        {
          name: "Del Valle Fresh",
          price: 8,
          photoUrl: "https://i.im.ge/2023/04/17/LLx3XS.DELVALE.jpg",
          description: "1,5L",
          category: "Bebidas",
        },
        {
          name: "Água mineral sem gás",
          price: 4,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202107091052_S8nc_p.jpg",
          description: "500ml",
          category: "Bebidas",
        },
        {
          name: "Coca-Cola Garrafa",
          price: 13,
          photoUrl: "https://andinacocacola.vtexassets.com/arquivos/ids/155948-1600-auto?v=637775304732100000&width=1600&height=auto&aspect=true",
          description: "1,5L",
          category: "Bebidas",
        },
        {
          name: "Coca-Cola Zero Garrafa",
          price: 13,
          photoUrl: "https://i.im.ge/2023/04/17/LLxHiD.COCA.png",
          description: "1,5L",
          category: "Bebidas",
        },
        {
          name: "Coca-Cola Litrão",
          price: 10.75,
          photoUrl: "https://i.im.ge/2023/04/17/LLxzXY.COCAA.webp",
          description: "1L",
          category: "Bebidas",
        },
        {
          name: "Coca-Cola Zero Litrão",
          price: 10.75,
          photoUrl: "https://i.im.ge/2023/04/17/LLxHiD.COCA.png",
          description: "1L",
          category: "Bebidas",
        },
        {
          name: "Guarana Antarctica Litrão",
          price: 8.50,
          photoUrl: "https://i.im.ge/2023/04/17/LLxfKM.guarana.webp",
          description: "1L",
          category: "Bebidas",
        },
        {
          name: "Guarana Antarctica Medio",
          price: 7.50,
          photoUrl: "https://i.im.ge/2023/04/17/LLxBpP.guarana600.webp",
          description: "600ml",
          category: "Bebidas",
        },
        {
          name: "Fanta Uva Medio",
          price: 7.50,
          photoUrl: "https://i.im.ge/2023/04/17/LL3Mwf.uva600.webp",
          description: "600ml",
          category: "Bebidas",
        },
        {
          name: "Fanta Laranja Medio",
          price: 7.50,
          photoUrl: "https://i.im.ge/2023/04/17/LL3QKm.fanta600.webp",
          description: "600ml",
          category: "Bebidas",
        },
        {
          name: "Sprite Medio",
          price: 8,
          photoUrl: "https://i.im.ge/2023/04/17/LL3olr.sprite.webp",
          description: "600ml",
          category: "Bebidas",
        },
        {
          name: "Coca-Cola Medio",
          price: 8,
          photoUrl: "https://i.im.ge/2023/04/17/LLxe21.coca600.webp",
          description: "600ml",
          category: "Bebidas",
        },
        {
          name: "Coca-Cola Zero Medio",
          price: 8,
          photoUrl: "https://i.im.ge/2023/04/17/LLxe21.coca600.webp",
          description: "600ml",
          category: "Bebidas",
        }
      ]
    });
  }
  const additions = await prisma.additions.findMany();
  if (additions.length === 0) {
    await prisma.additions.createMany({
      data: [
        {
          name: "Bife Normal",
          price: 4,
          photoUrl: "https://images.tcdn.com.br/img/img_prod/765092/hamburguer_carne_bovina_160g_preco_por_und_771_1_20200326162627.jpg",
          description: "+ Bife Normal",
          category: "Gostaria de acréscimo de Bife ?",
          quantity: 1,
        },
        {
          name: "Bife Artesanal",
          price: 8,
          photoUrl: "https://images.tcdn.com.br/img/img_prod/765092/hamburguer_100_angus_carne_bovina_150g_preco_por_und_1099_1_20200708120234.jpg",
          description: "+ Bife Artesanal",
          category: "Gostaria de acréscimo de Bife Artesanal ?",
          quantity: 1,
        },
        {
          name: "Calabresa",
          price: 5,
          photoUrl: "https://images.tcdn.com.br/img/img_prod/765092/calabresa_preco_por_kg_292_1_0295940945a20f2a2475b9dd76dc8095.jpg",
          description: " + Calabresa",
          category: "Gostaria de acréscimo de Calabresa ?",
          quantity: 1,
        },
        {
          name: "Chedeer",
          price: 4,
          photoUrl: "https://vixfrios.com.br/wp-content/uploads/2020/06/Cheddar-Cremoso.png",
          description: "Gostaria de acréscimo de Chedeer ?",
          category: "Deseja adicionar algo?",
          quantity: 1,
        },
        {
          name: "Catupiry",
          price: 4,
          photoUrl: "https://assets.vtex.app/unsafe/1020x930/center/middle/https%3A%2F%2Fcarrefourbrfood.vtexassets.com%2Farquivos%2Fids%2F190410%2F150606_1.jpg%3Fv%3D1768089842",
          description: "Gostaria de acréscimo de Catupiry ?",
          category: "Deseja adicionar algo?",
          quantity: 1,
        },
        {
          name: "Cream Cheese",
          price: 5,
          photoUrl: "https://img.itdg.com.br/tdg/images/blog/uploads/2016/09/533221a276b790bf983bb58d9a7b57d6-600x500.jpg",
          description: "Gostaria de acréscimo de Cream Cheese ?",
          category: "Deseja adicionar algo?",
          quantity: 1,
        },
        {
          name: "Bacon",
          price: 5,
          photoUrl: "https://cdn.minhareceita.com.br/2021/09/shutterstock_1051924499-1.jpg",
          description: "Gostaria de acréscimo de Bacon ?",
          category: "Deseja adicionar algo?",
          quantity: 1,
        },
        {
          name: "Ovo",
          price: 3,
          photoUrl: "https://i.im.ge/2023/04/17/LL3AEq.OVO.jpg",
          description: "Gostaria de acréscimo de Ovo ?",
          category: "Deseja adicionar algo?",
          quantity: 1,
        },
        {
          name: "Nossa Maionese Caseira",
          price: 1.5,
          photoUrl: "https://i.im.ge/2023/04/17/LL3Cvp.MAIONESE-FRIENDWS.jpg",
          description: "Gostaria de acréscimo da Nossa Maionese Caseira ?",
          category: "Deseja adicionar algo?",
          quantity: 1,
        },
        {
          name: "BATATA PEQUENA + REFRESCO GUARAMIL 290ML",
          price: 8.50,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202108221906_8MHT_i.jpg",
          description: "",
          category: "Complemente seu Lanche",
          quantity: 1,
        },
        {
          name: "BATATA PEQUENA + COCA LATA 220ML",
          price: 10.50,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202108221908_W1P7_i.jpg",
          description: "",
          category: "Complemente seu Lanche",
          quantity: 1,
        },
        {
          name: "BATATA PEQUENA + COCA LATA 350ML",
          price: 12.50,
          photoUrl: "https://static.ifood-static.com.br/image/upload/t_medium/pratos/94b6878e-f5dd-4ef1-9915-851853e1ab24/202108221910_B4EY_i.jpg",
          description: "",
          category: "Complemente seu Lanche",
          quantity: 1,
        },
        {
          name: "Amendoim",
          price: 1.00,
          photoUrl: "https://i.im.ge/2023/04/17/LL3Dcz.amendoin.png",
          description: "",
          category: "Complemente seu Açaí",
          quantity: 1,
        },
        {
          name: "Paçoca",
          price: 1.00,
          photoUrl: "https://i.im.ge/2023/04/17/LL3reT.pacoca.png",
          description: "",
          category: "Complemente seu Açaí",
          quantity: 1,
        },
        {
          name: "Granola",
          price: 2.50,
          photoUrl: "https://i.im.ge/2023/04/17/LL3d6a.granola.png",
          description: "",
          category: "Complemente seu Açaí",
          quantity: 1,
        },
        {
          name: "Leite em pó",
          price: 2.50,
          photoUrl: "https://i.im.ge/2023/04/17/LL31pG.leiteempo.png",
          description: "",
          category: "Complemente seu Açaí",
          quantity: 1,
        },
        {
          name: "Granulado",
          price: 2.50,
          photoUrl: "https://i.im.ge/2023/04/17/LL3wrM.granulado.webp",
          description: "",
          category: "Complemente seu Açaí",
          quantity: 1,
        },
        {
          name: "Cobertura de chocolate",
          price: 2.50,
          photoUrl: "https://i.im.ge/2023/04/17/LL3jVh.choclate.webp",
          description: "",
          category: "Complemente seu Açaí",
          quantity: 1,
        },
        {
          name: "Cobertura de Morango",
          price: 2.50,
          photoUrl: "https://i.im.ge/2023/04/17/LL3968.morango.webp",
          description: "",
          category: "Complemente seu Açaí",
          quantity: 1,
        },
        {
          name: "Cobertura de Uva",
          price: 2.50,
          photoUrl: "https://i.im.ge/2023/04/17/LL3iv9.uva.webp",
          description: "",
          category: "Complemente seu Açaí",
          quantity: 1,
        },
        {
          name: "Cobertura de Caramelo",
          price: 2.50,
          photoUrl: "https://i.im.ge/2023/04/17/LL35SX.b-be4f18260f304d8e8cf05cdbd66f6d95.jpg",
          description: "",
          category: "Complemente seu Açaí",
          quantity: 1,
        },
        {
          name: "Confete",
          price: 3,
          photoUrl: "https://i.im.ge/2023/04/17/LL3aly.confete.png",
          description: "",
          category: "Complemente seu Açaí",
          quantity: 1,
        },
        {
          name: "Kit Kat",
          price: 2.50,
          photoUrl: "https://i.im.ge/2023/04/17/LL3S2x.kitkat.png",
          description: "",
          category: "Complemente seu Açaí",
          quantity: 1,
        },
        {
          name: "Bis",
          price: 2.50,
          photoUrl: "https://i.im.ge/2023/04/17/LL3qKJ.biz.png",
          description: "",
          category: "Complemente seu Açaí",
          quantity: 1,
        },
        {
          name: "Ovomaltine",
          price: 3,
          photoUrl: "https://i.im.ge/2023/04/17/LL3OCL.ovomalte.png",
          description: "",
          category: "Complemente seu Açaí",
          quantity: 1,
        },
      ]
    });
  }
}
main()
  .catch((e) => {
    // eslint-disable-next-line no-console
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
