version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - backend/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: ./backend
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - backend/.env
    volumes:
      - node-modules:/app/node_modules
      - backend:/app
    command: npm run start

  react:
    container_name: react
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - react-volume:/var/www/html
    stdin_open: true
    privileged: true

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - react-volume:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - postgres
      - node
      - react
    privileged: true

volumes:
  postgres-volume:
  react-volume:
  node-modules:
  backend: