name: Pull Request on GitHub
on: [pull_request]
jobs:
  PullRequest-Github:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/check@v3
      - name: Make new .envfile
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_PORT: 5000
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "names"
          envkey_POSTGRES_URL: "postgresql://postgres:postgres@postgres:5432/names"
          directory: backend
          file_name: env.test
          fail_on_empty: true
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node npm run test